config/routes.rb
Rails.application.routes.draw do
  get 'incomings/index'
  get 'incomings/create'
  get 'incomings/destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :incomings, only: [:index, :new, :create, :destroy]
   root "incomings#index"


  get 'outgoings/index'
  get 'outgoings/create'
  get 'outgoings/destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :outgoings, only: [:index, :new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/incoming.rb
class Incoming < ActiveRecord::Base
    mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
    validates :name, presence: true # Make sure the owner's name is present.
    validates :رقم_مكاتبة_المركز, presence: true # Make sure the owner's number is present.
    validates :رقم_مكاتبة_الجهة_المعنية, presence: true # Make sure the owner's number is present.
    validates :تاريخ_المكاتبة, presence: true # Make sure the owner's number is present.
    validates :جهة_الوارد, presence: true # Make sure the owner's number is present.
    validates :طبيعة_المكاتبة, presence: true # Make sure the owner's number is present.
    validates :حالة_المكاتبة, presence: true # Make sure the owner's number is present.
    validates :الموضوع, presence: true # Make sure the owner's number is present.
    validates :الظابط_المختص, presence: true # Make sure the owner's number is present.
    validates :الموضوع_الرئيسى, presence: true # Make sure the owner's number is present.
end

app/models/outgoing.rb
class Outgoing < ApplicationRecord
    mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
    validates :رقم_المكاتبة, presence: true # Make sure the owner's number is present.
    validates :تاريخ_المكاتبة, presence: true # Make sure the owner's number is present.
    validates :الموضوع, presence: true # Make sure the owner's number is present.
    validates :جهة_الصادر, presence: true # Make sure the owner's number is present.
    validates :الظابط_المختص, presence: true # Make sure the owner's number is present.
    validates :وسيلة_الأرسال, presence: true # Make sure the owner's number is present.
    validates :ملاحظات, presence: true # Make sure the owner's number is present.
    validates :الموضوع_الرئيسى, presence: true # Make sure the owner's number is present.
end

app/models/resume.rb
class Resume < ActiveRecord::Base
    mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
    validates :name, presence: true # Make sure the owner's name is present.
    validates :رقم_مكاتبة_المركز, presence: true # Make sure the owner's number is present.
    validates :رقم_مكاتبة_الجهة_المعنية, presence: true # Make sure the owner's number is present.
    validates :تاريخ_المكاتبة, presence: true # Make sure the owner's number is present.
    validates :جهة_الوارد, presence: true # Make sure the owner's number is present.
    validates :طبيعة_المكاتبة, presence: true # Make sure the owner's number is present.
    validates :حالة_المكاتبة, presence: true # Make sure the owner's number is present.
    validates :الموضوع, presence: true # Make sure the owner's number is present.
    validates :الظابط_المختص, presence: true # Make sure the owner's number is present.
    validates :الموضوع_الرئيسى, presence: true # Make sure the owner's number is present.
 end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/incomings_controller.rb
class IncomingsController < ApplicationController
  def index
     @incoming = Incoming.all
  end
  
  def new
     @incoming = Incoming.new
  end
  
  def create
     @incoming = Incoming.new(incoming_params)
     
     if @incoming.save
        redirect_to incomings_path, notice: "The resume #{@incoming.name} has been uploaded."
     else
        render "new"
     end
     
  end
  
  def destroy
     @incoming = Incoming.find(params[:id])
     @incoming.destroy
     redirect_to incomings_path, notice:  "The resume #{@incoming.name} has been deleted."
  end
  
  private
     def incoming_params
     params.require(:incoming).permit(:name, :attachment , :رقم_مكاتبة_المركز, :رقم_مكاتبة_الجهة_المعنية, :تاريخ_المكاتبة, :جهة_الوارد, :طبيعة_المكاتبة, :حالة_المكاتبة, :الموضوع, :الظابط_المختص, :الموضوع_الرئيسى) 
end
  
end

app/controllers/outgoings_controller.rb
class OutgoingsController < ApplicationController
    def index
        @outgoings = Outgoing.all
     end
     
     def new
        @outgoings = Outgoing.new
     end
     
     def create
        @outgoings = Outgoing.new(outgoing_params)
        
        if @outgoings.save
           redirect_to outgoings_path, notice: "The outgoing #{@outgoings.name} has been uploaded."
        else
           render "new"
        end
        
     end
     
     def destroy
        @outgoings = Outgoing.find(params[:id])
        @outgoings.destroy
        redirect_to outgoings_path, notice:  "The outgoing #{@outgoings.name} has been deleted."
     end
     
     private
        def outgoing_params
        params.require(:outgoing).permit(:name, :attachment , :رقم_المكاتبة, :تاريخ_المكاتبة, :الموضوع, :جهة_الصادر, :الظابط_المختص, :وسيلة_الأرسال, :ملاحظات, :الموضوع_الرئيسى) 
   end
     
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/incomings_helper.rb
module IncomingsHelper
end

app/helpers/outgoings_helper.rb
module OutgoingsHelper
end

app/views/incomings/create.html.erb
<h1>Incomings#create</h1>
<p>Find me in app/views/incomings/create.html.erb</p>

app/views/incomings/destroy.html.erb
<h1>Incomings#destroy</h1>
<p>Find me in app/views/incomings/destroy.html.erb</p>

app/views/incomings/index.html.erb
<h1>Incomings#index</h1>
<p>Find me in app/views/incomings/index.html.erb</p>
<% if !flash[:notice].blank? %>
   <div class = "alert alert-info">
      <%= flash[:notice] %>
   </div>
<% end %>

<br />

<%= link_to "اضافة مكاتبة وارد", new_incoming_path, class: "btn btn-primary" %>

<%= link_to "اضافة مكاتبة صادر", new_outgoing_path, class: "btn btn-primary" %>

<br />
<br />
<%= search_field('xz','ds') %>

<table class = "table table-bordered table-striped">
   <thead>.
      <tr>
         <th>Name</th>
         <th>Download Link</th>
         <th>رقم مكاتبة المركز</th>
         <th> </th>
      </tr>
   </thead>
   
   <tbody>
      <% @incoming.each do |incoming| %>
         
         <tr>
            <td><%= incoming.name %></td>
            <td><%= link_to incoming.name, incoming.attachment_url %></td>
            <td><%= incoming.رقم_مكاتبة_المركز %></td>
            <td><%= button_to "Delete",  incoming, method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete #{incoming.name}?" %></td>

         </tr>
         
      <% end %>
   </tbody>
   
</table>

app/views/incomings/new.html.erb
<h1>Incomings#new</h1>
<p>Find me in app/views/incomings/new.html.erb</p>
<% if !@incoming.errors.empty? %>
   <div class = "alert alert-error">
      
      <ul>
         <% @incoming.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
         <% end %>
      </ul>
      
   </div>
<% end %>

   <div class = "well">
   <%= form_for @incoming, html: { multipart: true } do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.label :attachment %>
      <%= f.file_field :attachment %>


      <%= f.label :رقم_مكاتبة_المركز %>
      <%= f.text_field :رقم_مكاتبة_المركز %>
      
      <%= f.label :رقم_مكاتبة_الجهة_المعنية %>
      <%= f.text_field :رقم_مكاتبة_الجهة_المعنية %>


      <%= f.label :تاريخ_المكاتبة %>
      <%= date_field(:incoming, :تاريخ_المكاتبة) %>


      <%= f.label :جهة_الوارد %>                    
      <%= select(:incoming, :جهة_الوارد, [['اشارة'], ['ردار'], ['سيكرتارية عسكرية']]) %>


      <%= f.label :طبيعة_المكاتبة %>
      <%= select(:incoming, :طبيعة_المكاتبة, [['التزام'], ['معلومية'], ['مطلوب رد']]) %>


      <%= f.label :حالة_المكاتبة %>
      <%= select(:incoming, :حالة_المكاتبة, [['مغلقة'], ['منتهية']]) %>


      <%= f.label :الموضوع %>
      <%= f.text_field:الموضوع%>

      <%= f.label :الظابط_المختص %>
      <%= select(:incoming, :الظابط_المختص, [['رائد / محمود فوزى'], ['نقيب / بهى'], [' رائد/ احمد سمير']]) %>


      <%= f.label :الموضوع_الرئيسى %>
      <%= f.text_field:الموضوع_الرئيسى %>



      <%= f.submit "Save", class: "btn btn-primary" %>
   <% end %>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
   
   <head>
      <title>Mokatbat</title>
      <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
      <%
=begin%>
 <%= javascript_include_tag "application", "data-turbolinks-track" => true %> 
<%
=end%>
      <%= csrf_meta_tags %>
   </head>
   
   <body>
      <div class = "container" style = "padding-top:20px;">
         <%= yield %>
      </div>
   </body>

</html>

app/views/outgoings/create.html.erb
<h1>Outgoing#create</h1>
<p>Find me in app/views/outgoing/create.html.erb</p>

app/views/outgoings/destroy.html.erb
<h1>Outgoing#destroy</h1>
<p>Find me in app/views/outgoing/destroy.html.erb</p>

app/views/outgoings/index.html.erb
<h1>Outgoing#index</h1>
<p>Find me in app/views/outgoing/index.html.erb</p>
<% if !flash[:notice].blank? %>
   <div class = "alert alert-info">
      <%= flash[:notice] %>
   </div>
<% end %>

<br />

<%= link_to "اضافة مكاتبة وارد", new_incoming_path, class: "btn btn-primary" %>

<%= link_to "اضافة مكاتبة صادر", new_outgoing_path, class: "btn btn-primary" %>

<br />
<br />
<%= search_field('xz','ds') %>

<table class = "table table-bordered table-striped">
   <thead>.
      <tr>
         <th>جهة الصادر</th>
         <th>Download Link</th>
         <th>رقم مكاتبة المركز</th>
         <th> </th>
      </tr>
   </thead>
   
   <tbody>
      <% @outgoings.each do |outgoing| %>
         
         <tr>
            <td><%=  outgoing.جهة_الصادر %></td>
            <td><%= link_to outgoing.attachment_url, outgoing.attachment_url %></td>
            <td><%= outgoing.رقم_المكاتبة %></td>
            <td><%= button_to "Delete",  outgoing, method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete #{outgoing.name}?" %></td>

         </tr>
         
      <% end %>
   </tbody>
   
</table>

app/views/outgoings/new.html.erb
<h1>Outgoing#new</h1>
<p>Find me in app/views/outgoing/new.html.erb</p>
<% if !@outgoings.errors.empty? %>
   <div class = "alert alert-error">
      
      <ul>
         <% @outgoings.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
         <% end %>
      </ul>
      
   </div>
<% end %>

<div class = "well">
   <%= form_for @outgoings, html: { multipart: true } do |f| %>
      <%= f.label :attachment %>
      <%= f.file_field :attachment %>

      <%= f.label :رقم_مكاتبة %>
      <%= f.text_field :رقم_المكاتبة %>
      
      <%= f.label :تاريخ_المكاتبة %>
      <%= date_field(:outgoing, :تاريخ_المكاتبة) %>

      <%= f.label :الموضوع %>
      <%= f.text_field:الموضوع%>

      <%= f.label :جهة_الصادر %>                    
      <%= select(:outgoing, :جهة_الصادر, [['اشارة'], ['ردار'], ['سيكرتارية عسكرية']]) %> 

      <%= f.label :الظابط_المختص %>
      <%= select(:outgoing, :الظابط_المختص, [['رائد / محمود فوزى'], ['نقيب / بهى'], [' رائد/ احمد سمير']]) %>

      <%= f.label :وسيلة_الأرسال %>
      <%= select(:outgoing, :وسيلة_الأرسال, [['التزام'], ['معلومية'], ['مطلوب رد']]) %> 

      <%= f.label :ملاحظات%>
      <%= select(:outgoing, :ملاحظات, [['مغلقة'], ['منتهية']]) %> 

      <%= f.label :الموضوع_الرئيسى %>
      <%= f.text_field:الموضوع_الرئيسى %>
      
      <%= f.submit "Save", class: "btn btn-primary" %>

   <% end %>

</div>

app/views/resumes/index.html.erb
<h1>Resumes#index</h1>
<p>Find me in app/views/resumes/index.html.erb</p>
<% if !flash[:notice].blank? %>
   <div class = "alert alert-info">
      <%= flash[:notice] %>
   </div>
<% end %>

<br />

<%= link_to "اضافة مكاتبة وارد", new_resume_path(:type =>'incoming'), class: "btn btn-primary" %>

<%= link_to "اضافة مكاتبة صادر", new_resume_path(:type =>'outcoming'), class: "btn btn-primary" %>

<br />
<br />
<%= search_field('xz','ds') %>

<table class = "table table-bordered table-striped">
   <thead>.
      <tr>
         <th>Name</th>
         <th>Download Link</th>
         <th>رقم مكاتبة المركز</th>
         <th> </th>
      </tr>
   </thead>
   
   <tbody>
      <% @resumes.each do |resume| %>
         
         <tr>
            <td><%= resume.name %></td>
            <td><%= link_to resume.name, resume.attachment_url %></td>
            <td><%= resume.رقم_مكاتبة_المركز %></td>
            <td><%= button_to "Delete",  resume, method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete #{resume.name}?" %></td>

         </tr>
         
      <% end %>
   </tbody>
   
</table>

app/views/resumes/new.html.erb
<h1>Resumes#new</h1>
<p>Find me in app/views/resumes/new.html.erb</p>
<% if !@resume.errors.empty? %>
   <div class = "alert alert-error">
      
      <ul>
         <% @resume.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
         <% end %>
      </ul>
      
   </div>
<% end %>

   <div class = "well">
   <%= form_for @resume, html: { multipart: true } do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.label :attachment %>
      <%= f.file_field :attachment %>


      <%= f.label :رقم_مكاتبة_المركز %>
      <%= f.text_field :رقم_مكاتبة_المركز %>
      
      <%= f.label :رقم_مكاتبة_الجهة_المعنية %>
      <%= f.text_field :رقم_مكاتبة_الجهة_المعنية %>


      <%= f.label :تاريخ_المكاتبة %>
      <%= date_field(:resume, :تاريخ_المكاتبة) %>


      <%= f.label :جهة_الوارد %>                    
      <%= select(:resume, :جهة_الوارد, [['اشارة'], ['ردار'], ['سيكرتارية عسكرية']]) %>


      <%= f.label :طبيعة_المكاتبة %>
      <%= select(:resume, :طبيعة_المكاتبة, [['التزام'], ['معلومية'], ['مطلوب رد']]) %>


      <%= f.label :حالة_المكاتبة %>
      <%= select(:resume, :حالة_المكاتبة, [['مغلقة'], ['منتهية']]) %>


      <%= f.label :الموضوع %>
      <%= f.text_field:الموضوع%>

      <%= f.label :الظابط_المختص %>
      <%= select(:resume, :الظابط_المختص, [['رائد / محمود فوزى'], ['نقيب / بهى'], [' رائد/ احمد سمير']]) %>


      <%= f.label :الموضوع_الرئيسى %>
      <%= f.text_field:الموضوع_الرئيسى %>



      <%= f.submit "Save", class: "btn btn-primary" %>
   <% end %>


</div>